/*
  All site text in English, Portuguese and Spanish.

  - Fixed page text: the English is written in index.html (elements with
    data-i18n="key"); `strings.pt` / `strings.es` translate the same keys.
  - Projects, categories, disciplines, the career book and the labels the
    script writes live here in all three languages.
  - Images: `<slug>-1/2/3` in img/ (full size and -sm). Rebuild them from
    source/ with tools/build_images.py, which also prints the palettes.
*/
window.SITE = {
  workana: "https://www.workana.com/freelancer/84b58ec73a8e266de6ff8cce8992364c",

  categories: {
    "Branding": { en: "Branding", pt: "Branding", es: "Branding" },
    "Packaging": { en: "Packaging", pt: "Embalagem", es: "Packaging" },
    "Fashion": { en: "Fashion", pt: "Moda", es: "Moda" },
    "Illustration": { en: "Illustration", pt: "Ilustração", es: "Ilustración" },
    "Editorial": { en: "Editorial", pt: "Editorial", es: "Editorial" },
    "Spaces & 3D": { en: "Spaces & 3D", pt: "Espaços & 3D", es: "Espacios y 3D" },
    "Campaigns": { en: "Campaigns", pt: "Campanhas", es: "Campañas" },
    "Motion concepts": { en: "Motion concepts", pt: "Conceitos de motion", es: "Conceptos de motion" },
    "Digital": { en: "Digital", pt: "Digital", es: "Digital" },
  },

  /* The "Across disciplines" list: each row filters the work grid. */
  disciplines: [
    { cat: "Branding", img: "aurel-1", t: { en: "Brand identities", pt: "Identidades de marca", es: "Identidades de marca" } },
    { cat: "Packaging", img: "canto-2", t: { en: "Packaging & objects", pt: "Embalagens & objetos", es: "Packaging y objetos" } },
    { cat: "Editorial", img: "silent-archive-1", t: { en: "Books & editorial", pt: "Livros & editorial", es: "Libros y editorial" } },
    { cat: "Fashion", img: "afterhours-3", t: { en: "Fashion & textiles", pt: "Moda & têxteis", es: "Moda y textiles" } },
    { cat: "Illustration", img: "limon-1", t: { en: "Illustration & pattern", pt: "Ilustração & estampa", es: "Ilustración y estampado" } },
    { cat: "Spaces & 3D", img: "casa-calma-1", t: { en: "Spaces & imagined worlds", pt: "Espaços & mundos imaginados", es: "Espacios y mundos imaginados" } },
    { cat: "Campaigns", img: "brasa-3", t: { en: "Campaigns & visual storytelling", pt: "Campanhas & narrativa visual", es: "Campañas y narrativa visual" } },
    { cat: "Motion concepts", img: "atelier-08-1", t: { en: "Motion & film treatments", pt: "Motion & tratamentos de filme", es: "Motion y tratamientos de film" } },
    { cat: "Digital", img: "vela-1", t: { en: "Digital experiences", pt: "Experiências digitais", es: "Experiencias digitales" } },
  ],

  projects: [
    {
      slug: "aurel", name: "AUREL", cat: "Branding", stack: "Illustrator · Photoshop · InDesign",
      palette: ["#110101", "#431a13", "#6e4a2f", "#b8a28a", "#d3c5b4"],
      sub: { en: "Jewelry identity", pt: "Identidade para joalheria", es: "Identidad para joyería" },
      text: {
        en: "A refined jewelry identity pairing ivory paper, burgundy packaging, and sculptural gold forms. A study in quiet confidence, tactile materials, and editorial restraint.",
        pt: "Uma identidade refinada para joalheria que une papel marfim, embalagens bordô e formas esculturais em ouro. Um estudo de confiança silenciosa, materiais táteis e contenção editorial.",
        es: "Una identidad refinada para joyería que combina papel marfil, packaging burdeos y formas escultóricas en oro. Un estudio de confianza serena, materiales táctiles y contención editorial.",
      },
      caps: [
        { en: "Identity presentation", pt: "Apresentação da identidade", es: "Presentación de identidad" },
        { en: "Packaging study", pt: "Estudo de embalagem", es: "Estudio de packaging" },
        { en: "Editorial campaign", pt: "Campanha editorial", es: "Campaña editorial" },
      ],
    },
    {
      slug: "forma", name: "FORMA", cat: "Branding", stack: "Illustrator · Photoshop · Figma",
      palette: ["#062d94", "#39332c", "#59534b", "#b8ab9c", "#e0d9d1"],
      sub: { en: "Brand in space", pt: "Marca no espaço", es: "Marca en el espacio" },
      text: {
        en: "A contemporary identity built around cobalt geometry, architectural imagery, and a clear typographic voice. The system moves from personal stationery to large-scale public applications.",
        pt: "Uma identidade contemporânea construída com geometria em azul-cobalto, imagens de arquitetura e uma voz tipográfica clara. O sistema vai da papelaria pessoal a aplicações públicas em grande escala.",
        es: "Una identidad contemporánea construida con geometría en azul cobalto, imágenes de arquitectura y una voz tipográfica clara. El sistema va de la papelería personal a aplicaciones públicas a gran escala.",
      },
      caps: [
        { en: "Stationery suite", pt: "Papelaria", es: "Papelería" },
        { en: "Outdoor application", pt: "Aplicação externa", es: "Aplicación exterior" },
        { en: "Social collection", pt: "Coleção para redes sociais", es: "Colección para redes sociales" },
      ],
    },
    {
      slug: "canto", name: "CANTO", cat: "Packaging", stack: "Illustrator · Photoshop · Blender",
      palette: ["#360908", "#503c21", "#755735", "#9e8360", "#cead79"],
      sub: { en: "Artisan vermouth", pt: "Vermute artesanal", es: "Vermut artesanal" },
      text: {
        en: "Botanical illustration and rich, earthy color bring an artisan drinks concept to life. Bottle, gift box, and table setting explore a warm, considered retail experience.",
        pt: "Ilustração botânica e cores terrosas e intensas dão vida a um conceito de bebida artesanal. Garrafa, caixa de presente e mesa posta exploram uma experiência de varejo calorosa e cuidadosa.",
        es: "La ilustración botánica y un color terroso e intenso dan vida a un concepto de bebida artesanal. Botella, caja de regalo y mesa puesta exploran una experiencia de venta cálida y cuidada.",
      },
      caps: [
        { en: "Bottle hero", pt: "Garrafa em destaque", es: "Botella protagonista" },
        { en: "Gift packaging", pt: "Embalagem de presente", es: "Packaging de regalo" },
        { en: "Lifestyle presentation", pt: "Apresentação lifestyle", es: "Presentación lifestyle" },
      ],
    },
    {
      slug: "dolce", name: "DOLCE", cat: "Packaging", stack: "Illustrator · Photoshop · Blender",
      palette: ["#7b5a2c", "#ab8d62", "#b7a17b", "#d1b692", "#ead9bb"],
      sub: { en: "A sweeter ritual", pt: "Um ritual mais doce", es: "Un ritual más dulce" },
      text: {
        en: "A premium waffle-cone packaging study with elegant cylindrical tins, illustrated flavor cues, and gold finishes. The range balances shelf presence with the intimacy of a gift.",
        pt: "Um estudo de embalagem premium para casquinhas de waffle, com latas cilíndricas elegantes, sabores ilustrados e acabamentos dourados. A linha equilibra presença na prateleira com a intimidade de um presente.",
        es: "Un estudio de packaging premium para conos de barquillo, con latas cilíndricas elegantes, sabores ilustrados y acabados dorados. La línea equilibra presencia en el lineal con la intimidad de un regalo.",
      },
      caps: [
        { en: "Signature tin", pt: "Lata principal", es: "Lata principal" },
        { en: "Flavor collection", pt: "Coleção de sabores", es: "Colección de sabores" },
        { en: "Unboxing scene", pt: "Cena de unboxing", es: "Escena de unboxing" },
      ],
    },
    {
      slug: "nori", name: "NORI", cat: "Branding", stack: "Illustrator · Photoshop · InDesign",
      palette: ["#090a0e", "#23293b", "#d1b894", "#e1bb70", "#e1cfb4"],
      sub: { en: "Little people, bright days", pt: "Gente pequena, dias luminosos", es: "Gente pequeña, días luminosos" },
      text: {
        en: "A playful childrenswear concept built on navy, butter yellow, and soft geometric forms. Packaging, garment details, and campaign styling share an approachable retail language.",
        pt: "Um conceito lúdico de moda infantil construído com azul-marinho, amarelo-manteiga e formas geométricas suaves. Embalagens, detalhes das peças e styling de campanha compartilham uma linguagem de varejo acolhedora.",
        es: "Un concepto lúdico de moda infantil construido con azul marino, amarillo mantequilla y formas geométricas suaves. Packaging, detalles de las prendas y estilismo de campaña comparten un lenguaje de venta cercano.",
      },
      caps: [
        { en: "Retail packaging", pt: "Embalagem de loja", es: "Packaging de tienda" },
        { en: "Garment labels", pt: "Etiquetas das peças", es: "Etiquetas de prenda" },
        { en: "Collection campaign", pt: "Campanha da coleção", es: "Campaña de colección" },
      ],
    },
    {
      slug: "vector", name: "VECTOR", cat: "Fashion", stack: "CLO 3D · Illustrator · Blender · Photoshop",
      palette: ["#151617", "#313232", "#545651", "#6b6e62", "#a0a77c"],
      sub: { en: "Performance in detail", pt: "Performance nos detalhes", es: "Rendimiento en cada detalle" },
      text: {
        en: "A sportswear design study exploring compression silhouettes, engineered seam lines, and tactile fabric surfaces. Graphite and electric lime establish a precise athletic direction.",
        pt: "Um estudo de design esportivo que explora silhuetas de compressão, costuras técnicas e superfícies de tecido táteis. Grafite e verde-limão elétrico definem uma direção atlética precisa.",
        es: "Un estudio de ropa deportiva que explora siluetas de compresión, costuras técnicas y superficies textiles táctiles. Grafito y verde lima eléctrico marcan una dirección atlética precisa.",
      },
      caps: [
        { en: "Front concept", pt: "Conceito frontal", es: "Concepto frontal" },
        { en: "Rear concept", pt: "Conceito traseiro", es: "Concepto trasero" },
        { en: "Material detail", pt: "Detalhe do material", es: "Detalle del material" },
      ],
    },
    {
      slug: "afterhours", name: "AFTERHOURS", cat: "Fashion", stack: "Illustrator · Photoshop",
      palette: ["#12100d", "#312b25", "#4e4339", "#655f57", "#a4917f"],
      sub: { en: "Same sky, different angles", pt: "Mesmo céu, outros ângulos", es: "Mismo cielo, otros ángulos" },
      text: {
        en: "An expressive streetwear capsule combining distressed typography, orbital imagery, and washed black textiles. Graphic exploration extends into garment applications and editorial styling.",
        pt: "Uma cápsula de streetwear expressiva que combina tipografia desgastada, imagens orbitais e tecidos pretos lavados. A exploração gráfica se estende às peças e ao styling editorial.",
        es: "Una cápsula de streetwear expresiva que combina tipografía desgastada, imágenes orbitales y tejidos negros lavados. La exploración gráfica se extiende a las prendas y al estilismo editorial.",
      },
      caps: [
        { en: "Graphic study", pt: "Estudo gráfico", es: "Estudio gráfico" },
        { en: "Garment application", pt: "Aplicação na peça", es: "Aplicación en prenda" },
        { en: "Fashion campaign", pt: "Campanha de moda", es: "Campaña de moda" },
      ],
    },
    {
      slug: "limon", name: "LIMON", cat: "Illustration", stack: "Photoshop · Illustrator",
      palette: ["#6c5930", "#988b69", "#bca67e", "#c3b69d", "#d6c7b3"],
      sub: { en: "The lemon grove collection", pt: "A coleção do limoal", es: "La colección del limonar" },
      text: {
        en: "A botanical textile concept inspired by watercolor, summer kitchens, and the natural texture of linen. Lemons, leafy branches, and small flowers form a relaxed homeware language.",
        pt: "Um conceito têxtil botânico inspirado na aquarela, nas cozinhas de verão e na textura natural do linho. Limões, ramos e pequenas flores formam uma linguagem descontraída para casa.",
        es: "Un concepto textil botánico inspirado en la acuarela, las cocinas de verano y la textura natural del lino. Limones, ramas y pequeñas flores forman un lenguaje relajado para el hogar.",
      },
      caps: [
        { en: "Pattern direction", pt: "Direção da estampa", es: "Dirección del estampado" },
        { en: "Textile application", pt: "Aplicação têxtil", es: "Aplicación textil" },
        { en: "Homeware collection", pt: "Coleção casa", es: "Colección hogar" },
      ],
    },
    {
      slug: "silent-archive", name: "The Silent Archive", cat: "Editorial", stack: "Photoshop · InDesign · Illustrator",
      palette: ["#050608", "#33130d", "#433327", "#957861", "#a98f79"],
      sub: { en: "A story hidden in the margins", pt: "Uma história escondida nas margens", es: "Una historia escondida en los márgenes" },
      text: {
        en: "A literary thriller cover exploration built from archival fragments, shadowed doorways, and a single red thread. The imagery suggests memory, investigation, and stories waiting to be discovered.",
        pt: "Uma exploração de capa para um thriller literário, construída com fragmentos de arquivo, portas na penumbra e um único fio vermelho. As imagens sugerem memória, investigação e histórias à espera de serem descobertas.",
        es: "Una exploración de portada para un thriller literario, construida con fragmentos de archivo, puertas en penumbra y un único hilo rojo. Las imágenes sugieren memoria, investigación e historias esperando ser descubiertas.",
      },
      caps: [
        { en: "Cover exploration", pt: "Exploração de capa", es: "Exploración de portada" },
        { en: "Book presentation", pt: "Apresentação do livro", es: "Presentación del libro" },
        { en: "Launch campaign", pt: "Campanha de lançamento", es: "Campaña de lanzamiento" },
      ],
    },
    {
      slug: "small-hours", name: "Small Hours", cat: "Editorial", stack: "InDesign · Photoshop · Acrobat Pro",
      palette: ["#22150f", "#5c4737", "#9c8571", "#bdb1a4", "#dfd2c4"],
      sub: { en: "Room for the story", pt: "Espaço para a história", es: "Espacio para la historia" },
      text: {
        en: "An editorial concept using generous margins, restrained serif typography, and atmospheric imagery. Chapter openers, interior spreads, and a book presentation explore a calm reading experience.",
        pt: "Um conceito editorial com margens generosas, tipografia serifada contida e imagens atmosféricas. Aberturas de capítulo, páginas internas e a apresentação do livro exploram uma leitura tranquila.",
        es: "Un concepto editorial con márgenes generosos, tipografía serif contenida e imágenes atmosféricas. Aperturas de capítulo, páginas interiores y la presentación del libro exploran una lectura tranquila.",
      },
      caps: [
        { en: "Chapter opener", pt: "Abertura de capítulo", es: "Apertura de capítulo" },
        { en: "Interior spread", pt: "Página dupla interna", es: "Doble página interior" },
        { en: "Book and bookmark", pt: "Livro e marcador", es: "Libro y marcapáginas" },
      ],
    },
    {
      slug: "little-strikers", name: "Little Strikers", cat: "Illustration", stack: "Photoshop · Illustrator · InDesign",
      palette: ["#11100d", "#48423c", "#958c82", "#dfd7cb", "#f4eee2"],
      sub: { en: "An adventure in every match", pt: "Uma aventura em cada partida", es: "Una aventura en cada partido" },
      text: {
        en: "A black-and-white football adventure following a young player from discovery to a decisive match and team celebration. Expressive characters and cinematic compositions carry the story.",
        pt: "Uma aventura de futebol em preto e branco que acompanha um jovem jogador da descoberta até a partida decisiva e a comemoração com o time. Personagens expressivos e composições cinematográficas conduzem a história.",
        es: "Una aventura de fútbol en blanco y negro que sigue a un joven jugador desde el descubrimiento hasta el partido decisivo y la celebración con su equipo. Personajes expresivos y composiciones cinematográficas llevan la historia.",
      },
      caps: [
        { en: "The discovery", pt: "A descoberta", es: "El descubrimiento" },
        { en: "The decisive moment", pt: "O momento decisivo", es: "El momento decisivo" },
        { en: "The celebration", pt: "A comemoração", es: "La celebración" },
      ],
    },
    {
      slug: "casa-calma", name: "CASA CALMA", cat: "Spaces & 3D", stack: "Blender · Cycles · Photoshop",
      palette: ["#42240d", "#684d30", "#886643", "#a98867", "#ceb59b"],
      sub: { en: "Architecture for slower living", pt: "Arquitetura para viver sem pressa", es: "Arquitectura para vivir sin prisa" },
      text: {
        en: "A contemporary residential concept explored through travertine, walnut, limewash, and warm natural light. Exterior, living, and kitchen studies share a tactile architectural mood.",
        pt: "Um conceito residencial contemporâneo explorado com travertino, nogueira, pintura à cal e luz natural quente. Os estudos de fachada, sala e cozinha compartilham uma atmosfera arquitetônica tátil.",
        es: "Un concepto residencial contemporáneo explorado con travertino, nogal, pintura a la cal y luz natural cálida. Los estudios de exterior, salón y cocina comparten una atmósfera arquitectónica táctil.",
      },
      caps: [
        { en: "Courtyard exterior", pt: "Pátio externo", es: "Patio exterior" },
        { en: "Living space", pt: "Sala de estar", es: "Salón" },
        { en: "Kitchen study", pt: "Estudo da cozinha", es: "Estudio de cocina" },
      ],
    },
    {
      slug: "moss", name: "MOSS", cat: "Spaces & 3D", stack: "Blender · Photoshop",
      palette: ["#292b20", "#583a25", "#505548", "#437670", "#f3cca7"],
      sub: { en: "A small world, richly imagined", pt: "Um pequeno mundo, ricamente imaginado", es: "Un pequeño mundo, ricamente imaginado" },
      text: {
        en: "A stylized wildlife world combining a faceted fox character with atmospheric forest scenes. Angular forms, warm light, and a restrained natural palette create a distinctive visual language.",
        pt: "Um mundo selvagem estilizado que combina uma raposa facetada com cenas atmosféricas de floresta. Formas angulares, luz quente e uma paleta natural contida criam uma linguagem visual própria.",
        es: "Un mundo salvaje estilizado que combina un zorro facetado con escenas atmosféricas de bosque. Formas angulares, luz cálida y una paleta natural contenida crean un lenguaje visual propio.",
      },
      caps: [
        { en: "Character study", pt: "Estudo de personagem", es: "Estudio de personaje" },
        { en: "Environment study", pt: "Estudo de cenário", es: "Estudio de entorno" },
        { en: "Narrative scene", pt: "Cena narrativa", es: "Escena narrativa" },
      ],
    },
    {
      slug: "luma", name: "LUMA", cat: "Campaigns", stack: "Blender · Photoshop · After Effects",
      palette: ["#d79c73", "#e8bb97", "#f5d0af", "#e8d9cf", "#fdf2e1"],
      sub: { en: "The daily ritual", pt: "O ritual diário", es: "El ritual diario" },
      text: {
        en: "A sculptural beauty campaign concept exploring pearl surfaces, translucent water, and apricot light. Product and material studies build a soft, luminous visual identity.",
        pt: "Um conceito de campanha de beleza escultural que explora superfícies peroladas, água translúcida e luz cor de damasco. Estudos de produto e material constroem uma identidade visual suave e luminosa.",
        es: "Un concepto de campaña de belleza escultural que explora superficies nacaradas, agua translúcida y luz color albaricoque. Los estudios de producto y material construyen una identidad visual suave y luminosa.",
      },
      caps: [
        { en: "Product hero", pt: "Produto em destaque", es: "Producto protagonista" },
        { en: "Water study", pt: "Estudo com água", es: "Estudio con agua" },
        { en: "Campaign visual", pt: "Peça de campanha", es: "Pieza de campaña" },
      ],
    },
    {
      slug: "pulse", name: "PULSE", cat: "Motion concepts", stack: "After Effects · Premiere Pro · Blender",
      palette: ["#03030c", "#120f2b", "#1e2950", "#3a386f", "#866bc4"],
      sub: { en: "Play next", pt: "A próxima partida", es: "La próxima partida" },
      text: {
        en: "Three keyframes for a gaming-store promotion, moving from a dramatic controller reveal to a game showcase and closing brand frame. Chrome, violet, and cyan give the sequence its energy.",
        pt: "Três quadros-chave para a promoção de uma loja de games, da revelação dramática do controle à vitrine de jogos e ao quadro final da marca. Cromo, violeta e ciano dão energia à sequência.",
        es: "Tres fotogramas clave para la promoción de una tienda de videojuegos, desde la revelación dramática del mando hasta el escaparate de juegos y el cierre de marca. Cromo, violeta y cian dan energía a la secuencia.",
      },
      caps: [
        { en: "Opening keyframe", pt: "Quadro de abertura", es: "Fotograma de apertura" },
        { en: "Showcase keyframe", pt: "Quadro de vitrine", es: "Fotograma de escaparate" },
        { en: "Closing keyframe", pt: "Quadro de encerramento", es: "Fotograma de cierre" },
      ],
    },
    {
      slug: "atelier-08", name: "ATELIER 08", cat: "Motion concepts", stack: "Premiere Pro · DaVinci Resolve · After Effects",
      palette: ["#0a0a08", "#4a0b0a", "#31261d", "#9d856c", "#bba68d"],
      sub: { en: "A study in silhouette", pt: "Um estudo de silhueta", es: "Un estudio de silueta" },
      text: {
        en: "A fashion-film treatment bringing cream tailoring into dramatic architectural settings. A hero composition, tactile close-up, and closing brand frame establish the proposed visual rhythm.",
        pt: "Um tratamento de filme de moda que leva a alfaiataria creme a cenários arquitetônicos dramáticos. Uma composição principal, um close tátil e o quadro final da marca definem o ritmo visual proposto.",
        es: "Un tratamiento de fashion film que lleva la sastrería crema a escenarios arquitectónicos dramáticos. Una composición principal, un primer plano táctil y el cierre de marca definen el ritmo visual propuesto.",
      },
      caps: [
        { en: "Hero keyframe", pt: "Quadro principal", es: "Fotograma principal" },
        { en: "Material keyframe", pt: "Quadro de material", es: "Fotograma de material" },
        { en: "Closing keyframe", pt: "Quadro de encerramento", es: "Fotograma de cierre" },
      ],
    },
    {
      slug: "orbit", name: "ORBIT", cat: "Motion concepts", stack: "Premiere Pro · After Effects · Illustrator · Audition",
      palette: ["#060e21", "#161f39", "#383752", "#9e8ea6", "#f2e4e3"],
      sub: { en: "Make room for focus", pt: "Abra espaço para o foco", es: "Haz espacio para el foco" },
      text: {
        en: "An explainer treatment for a productivity concept. The three visual beats move from everyday overload to organization and a calm closing invitation.",
        pt: "Um tratamento de vídeo explicativo para um conceito de produtividade. Os três momentos visuais vão da sobrecarga do dia a dia à organização e a um convite final tranquilo.",
        es: "Un tratamiento de video explicativo para un concepto de productividad. Los tres momentos visuales van de la sobrecarga diaria a la organización y a una invitación final tranquila.",
      },
      caps: [
        { en: "The problem", pt: "O problema", es: "El problema" },
        { en: "The product idea", pt: "A ideia do produto", es: "La idea del producto" },
        { en: "The closing invitation", pt: "O convite final", es: "La invitación final" },
      ],
    },
    {
      slug: "brasa", name: "BRASA", cat: "Campaigns", stack: "Photoshop · Illustrator · InDesign",
      palette: ["#0e0301", "#48240f", "#7d2705", "#b07b4d", "#dac3a8"],
      sub: { en: "Gather around the fire", pt: "Reunidos em volta do fogo", es: "Reunidos alrededor del fuego" },
      text: {
        en: "A restaurant campaign built around fire-grilled food, warm light, and refined typography. Food imagery, a menu study, and an advertisement express a generous, sensory dining experience.",
        pt: "Uma campanha de restaurante construída em torno da comida na brasa, da luz quente e de uma tipografia refinada. Fotos de pratos, um estudo de cardápio e um anúncio expressam uma experiência generosa e sensorial.",
        es: "Una campaña de restaurante construida en torno a la comida a la brasa, la luz cálida y una tipografía refinada. Imágenes de platos, un estudio de menú y un anuncio expresan una experiencia generosa y sensorial.",
      },
      caps: [
        { en: "Food hero", pt: "Prato em destaque", es: "Plato protagonista" },
        { en: "Menu concept", pt: "Conceito de cardápio", es: "Concepto de menú" },
        { en: "Campaign visual", pt: "Peça de campanha", es: "Pieza de campaña" },
      ],
    },
    {
      slug: "vela", name: "VELA", cat: "Digital", stack: "Figma · HTML · CSS · JavaScript",
      palette: ["#695c3e", "#998161", "#b6a083", "#cdb99e", "#ece2d3"],
      sub: { en: "Simple by nature", pt: "Simples por natureza", es: "Simple por naturaleza" },
      text: {
        en: "A skincare commerce concept pairing spacious layouts and clear hierarchy with botanical product imagery. Desktop, mobile, and advertising studies explore a consistent customer experience.",
        pt: "Um conceito de e-commerce de skincare que une layouts arejados e hierarquia clara a imagens botânicas de produto. Estudos para desktop, mobile e anúncios exploram uma experiência de compra consistente.",
        es: "Un concepto de e-commerce de cuidado de la piel que une diseños amplios y jerarquía clara con imágenes botánicas de producto. Estudios para escritorio, móvil y publicidad exploran una experiencia de compra coherente.",
      },
      caps: [
        { en: "Desktop concept", pt: "Conceito desktop", es: "Concepto escritorio" },
        { en: "Mobile concept", pt: "Conceito mobile", es: "Concepto móvil" },
        { en: "Campaign creative", pt: "Criativo de campanha", es: "Creatividad de campaña" },
      ],
    },
    {
      slug: "sonora", name: "SONORA", cat: "Campaigns", stack: "Illustrator · Photoshop · After Effects",
      palette: ["#031032", "#032a82", "#f95f51", "#ddcab7", "#f4e1c7"],
      sub: { en: "Night. Sound. City.", pt: "Noite. Som. Cidade.", es: "Noche. Sonido. Ciudad." },
      text: {
        en: "An expressive music-event identity exploring experimental typography, sound-wave forms, and a vivid blue-and-coral palette. Poster, outdoor, and social studies carry the energy across formats.",
        pt: "Uma identidade expressiva para um evento de música que explora tipografia experimental, formas de ondas sonoras e uma paleta vibrante de azul e coral. Estudos de pôster, mídia externa e redes sociais levam essa energia a todos os formatos.",
        es: "Una identidad expresiva para un evento musical que explora tipografía experimental, formas de ondas sonoras y una paleta vibrante de azul y coral. Estudios de póster, exterior y redes sociales llevan esa energía a todos los formatos.",
      },
      caps: [
        { en: "Poster study", pt: "Estudo de pôster", es: "Estudio de póster" },
        { en: "Outdoor application", pt: "Aplicação externa", es: "Aplicación exterior" },
        { en: "Social announcement", pt: "Anúncio para redes sociais", es: "Anuncio para redes sociales" },
      ],
    },
  ],

  /* Labels the script writes into the page. */
  ui: {
    en: { all: "All", project: "project", projects: "projects", visuals: "3 visuals", view: "View", open: "Open", close: "Close", filter: "Filter", concept: "Concept study", stack: "Suggested production stack", palette: "Palette", next: "Next project", end: "Independent concept exploration", endMotion: "Still keyframes / visual treatment", motion: "Motion effects", on: "On", off: "Off" },
    pt: { all: "Todos", project: "projeto", projects: "projetos", visuals: "3 visuais", view: "Ver", open: "Abrir", close: "Fechar", filter: "Filtrar", concept: "Estudo de conceito", stack: "Stack de produção sugerido", palette: "Paleta", next: "Próximo projeto", end: "Exploração de conceito independente", endMotion: "Quadros-chave estáticos / tratamento visual", motion: "Efeitos de movimento", on: "Ligados", off: "Desligados" },
    es: { all: "Todos", project: "proyecto", projects: "proyectos", visuals: "3 visuales", view: "Ver", open: "Abrir", close: "Cerrar", filter: "Filtrar", concept: "Estudio de concepto", stack: "Stack de producción sugerido", palette: "Paleta", next: "Siguiente proyecto", end: "Exploración de concepto independiente", endMotion: "Fotogramas clave fijos / tratamiento visual", motion: "Efectos de movimiento", on: "Activados", off: "Desactivados" },
  },

  /* The "My Career" book. Facts come from the public Workana profile (6 Oct 2026). */
  career: {
    craft: [
      { lvl: 4, t: { en: "Photoshop", pt: "Photoshop", es: "Photoshop" } },
      { lvl: 4, t: { en: "Sound design", pt: "Sound design", es: "Diseño sonoro" } },
      { lvl: 3, t: { en: "Graphic design", pt: "Design gráfico", es: "Diseño gráfico" } },
      { lvl: 3, t: { en: "Illustration", pt: "Ilustração", es: "Ilustración" } },
      { lvl: 3, t: { en: "Logo design", pt: "Design de logo", es: "Diseño de logo" } },
      { lvl: 3, t: { en: "Video production", pt: "Produção de vídeo", es: "Producción de video" } },
      { lvl: 2, t: { en: "3D rendering", pt: "Renderização 3D", es: "Render 3D" } },
      { lvl: 2, t: { en: "UI design", pt: "Design de interface", es: "Diseño de interfaz" } },
      { lvl: 2, t: { en: "After Effects", pt: "After Effects", es: "After Effects" } },
    ],
    years: {
      4: { en: "10+ yrs", pt: "10+ anos", es: "10+ años" },
      3: { en: "5–10 yrs", pt: "5–10 anos", es: "5–10 años" },
      2: { en: "3–5 yrs", pt: "3–5 anos", es: "3–5 años" },
    },
    services: [
      { t: { en: "Brand identity", pt: "Identidade de marca", es: "Identidad de marca" }, d: { en: "Logo, type, colour and packaging", pt: "Logo, tipografia, cor e embalagem", es: "Logo, tipografía, color y packaging" } },
      { t: { en: "Editorial design", pt: "Design editorial", es: "Diseño editorial" }, d: { en: "Books, covers and layouts", pt: "Livros, capas e diagramação", es: "Libros, portadas y maquetación" } },
      { t: { en: "3D visualization", pt: "Visualização 3D", es: "Visualización 3D" }, d: { en: "Architecture, interiors and products", pt: "Arquitetura, interiores e produtos", es: "Arquitectura, interiores y productos" } },
      { t: { en: "Product imagery & retouching", pt: "Imagem de produto e retoque", es: "Imagen de producto y retoque" }, d: { en: "Ready for online stores", pt: "Pronta para lojas online", es: "Lista para tiendas online" } },
      { t: { en: "Motion & video", pt: "Motion e vídeo", es: "Motion y video" }, d: { en: "Editing, motion graphics, 3D animation", pt: "Edição, motion graphics, animação 3D", es: "Edición, motion graphics, animación 3D" } },
      { t: { en: "Sound design", pt: "Sound design", es: "Diseño sonoro" }, d: { en: "Cleanup, mixing, soundscapes", pt: "Limpeza, mixagem, ambiências", es: "Limpieza, mezcla, ambientes" } },
      { t: { en: "UI/UX design", pt: "Design UI/UX", es: "Diseño UI/UX" }, d: { en: "Web and mobile, prototype-ready", pt: "Web e mobile, pronto para protótipo", es: "Web y móvil, listo para prototipo" } },
    ],
    thumbs: ["aurel-1", "canto-1", "silent-archive-1", "casa-calma-2", "luma-1", "sonora-1"],
    text: {
      en: {
        title: "My Career", vol: "Volume I · 2026", exlibris: "Ex libris", role: "Graphic designer & digital creative", place: "Brazil",
        ch: "Chapter",
        c1t: "The designer",
        c1p: "As a multidisciplinary graphic designer and digital creative, I make premium visuals for brands, products, e-commerce and digital platforms: polished, realistic images that stay clear, functional and useful for selling.",
        c1q: "I value visual quality, attention to detail, clear communication and reliable delivery.",
        langs: "Languages", l1: "Portuguese", l1v: "native", l2: "English", l2v: "high intermediate", l3: "Spanish", l3v: "basic",
        c2t: "Craft & years", c2note: "Years of experience as listed on my Workana profile.",
        c3t: "On Workana", rating: "average client rating", done: "projects delivered", reviews: "client reviews",
        level: "Bronze level · member since September 2026", eng: "Workana English test: 80%, top 12%",
        recent: "Delivered work",
        job1: "Image editing & retouching for web and e-commerce", job1w: "Client in Spain",
        job2: "Editorial layout of a 175-page book", job2w: "Client in Brazil",
        c4t: "In a client's words",
        quote: "A very good experience working with her. She understood exactly what we were looking for from the start and turned it into a professional, modern and carefully crafted design. I would especially highlight her attention to detail, good communication and willingness to make changes and improvements throughout the project.",
        by: "Angel E., Spain", qnote: "Translated from Spanish",
        q1: "Communication", q2: "Deadlines", q3: "Quality",
        c5t: "What I make",
        c6t: "The collection", c6p: "Twenty concept studies across nine disciplines: sixty visuals made to show range, from identities on paper to worlds on screen.", c6link: "See the work",
        c7t: "The next chapter is <em>yours.</em>", c7p: "Send me your brief on Workana. I reply in Portuguese and English, and I also take briefs in Spanish.", c7cta: "Hire me on Workana", sign: "Nayara",
        back: "Selected Works · 2026",
        prev: "Previous page", next: "Next page", close: "Close the book", hint: "Click a page or use ← → to turn it",
      },
      pt: {
        title: "Minha Carreira", vol: "Volume I · 2026", exlibris: "Ex libris", role: "Designer gráfica e criativa digital", place: "Brasil",
        ch: "Capítulo",
        c1t: "A designer",
        c1p: "Sou designer gráfica e criativa digital multidisciplinar. Crio visuais premium para marcas, produtos, e-commerce e plataformas digitais: imagens sofisticadas e realistas, sem perder clareza, funcionalidade e foco comercial.",
        c1q: "Valorizo qualidade visual, atenção aos detalhes, comunicação clara e entregas profissionais.",
        langs: "Idiomas", l1: "Português", l1v: "nativo", l2: "Inglês", l2v: "intermediário alto", l3: "Espanhol", l3v: "básico",
        c2t: "Ofício & anos", c2note: "Anos de experiência conforme meu perfil no Workana.",
        c3t: "No Workana", rating: "nota média dos clientes", done: "projetos entregues", reviews: "avaliações de clientes",
        level: "Nível Bronze · membro desde setembro de 2026", eng: "Teste de inglês do Workana: 80%, top 12%",
        recent: "Trabalhos entregues",
        job1: "Edição e retoque de imagens para web e e-commerce", job1w: "Cliente na Espanha",
        job2: "Diagramação editorial de um livro de 175 páginas", job2w: "Cliente no Brasil",
        c4t: "Nas palavras de um cliente",
        quote: "Uma experiência muito boa trabalhando com ela. Entendeu perfeitamente o que buscávamos desde o início e soube transformar isso em um design profissional, moderno e muito cuidadoso. Destaco especialmente sua atenção aos detalhes, a boa comunicação e a disposição para fazer mudanças e melhorias durante todo o projeto.",
        by: "Angel E., Espanha", qnote: "Traduzido do espanhol",
        q1: "Comunicação", q2: "Prazos", q3: "Qualidade",
        c5t: "O que eu crio",
        c6t: "A coleção", c6p: "Vinte estudos de conceito em nove disciplinas: sessenta visuais feitos para mostrar alcance, da identidade no papel a mundos na tela.", c6link: "Ver os trabalhos",
        c7t: "O próximo capítulo é <em>seu.</em>", c7p: "Envie seu briefing pelo Workana. Respondo em português e inglês, e também recebo briefings em espanhol.", c7cta: "Contratar no Workana", sign: "Nayara",
        back: "Selected Works · 2026",
        prev: "Página anterior", next: "Próxima página", close: "Fechar o livro", hint: "Clique numa página ou use ← → para virar",
      },
      es: {
        title: "Mi Carrera", vol: "Volumen I · 2026", exlibris: "Ex libris", role: "Diseñadora gráfica y creativa digital", place: "Brasil",
        ch: "Capítulo",
        c1t: "La diseñadora",
        c1p: "Soy diseñadora gráfica y creativa digital multidisciplinaria. Creo visuales premium para marcas, productos, e-commerce y plataformas digitales: imágenes pulidas y realistas que además son claras, funcionales y útiles para vender.",
        c1q: "Valoro la calidad visual, la atención al detalle, la comunicación clara y las entregas profesionales.",
        langs: "Idiomas", l1: "Portugués", l1v: "nativo", l2: "Inglés", l2v: "intermedio alto", l3: "Español", l3v: "básico",
        c2t: "Oficio y años", c2note: "Años de experiencia según mi perfil de Workana.",
        c3t: "En Workana", rating: "calificación media de clientes", done: "proyectos entregados", reviews: "reseñas de clientes",
        level: "Nivel Bronce · miembro desde septiembre de 2026", eng: "Prueba de inglés de Workana: 80%, top 12%",
        recent: "Trabajos entregados",
        job1: "Edición y retoque de imágenes para web y e-commerce", job1w: "Cliente en España",
        job2: "Maquetación editorial de un libro de 175 páginas", job2w: "Cliente en Brasil",
        c4t: "En palabras de un cliente",
        quote: "Muy buena experiencia trabajando con ella. Ha entendido perfectamente lo que buscábamos desde el principio y ha sabido trasladarlo a un diseño profesional, moderno y muy cuidado. Destacaría especialmente su atención al detalle, buena comunicación y predisposición para realizar cambios y mejoras durante todo el proyecto.",
        by: "Angel E., España", qnote: "",
        q1: "Comunicación", q2: "Plazos", q3: "Calidad",
        c5t: "Lo que creo",
        c6t: "La colección", c6p: "Veinte estudios de concepto en nueve disciplinas: sesenta visuales hechos para mostrar alcance, de identidades en papel a mundos en pantalla.", c6link: "Ver los trabajos",
        c7t: "El próximo capítulo es <em>tuyo.</em>", c7p: "Envíame tu brief por Workana. Respondo en portugués e inglés, y también recibo briefs en español.", c7cta: "Contrátame en Workana", sign: "Nayara",
        back: "Selected Works · 2026",
        prev: "Página anterior", next: "Página siguiente", close: "Cerrar el libro", hint: "Haz clic en una página o usa ← → para pasarla",
      },
    },
  },

  /* Translations of the fixed page text in index.html. */
  strings: {
    pt: {
      "skip": "Pular para os trabalhos", "a.langs": "Idioma", "a.filters": "Filtrar projetos", "a.nav": "Seções",
      "nav.work": "Trabalhos", "nav.disc": "Disciplinas", "nav.career": "Carreira", "nav.contact": "Contato",
      "btn.career": "Minha Carreira", "btn.careerSub": "Abrir o livro",
      "hero.eyebrow": "Direção de arte · Design · Narrativa visual",
      "hero.title": "<span class=\"ln\"><span>Um ponto</span></span> <span class=\"ln\"><span>de <em class=\"foil\">vista.</em></span></span>",
      "hero.intro": "Identidades únicas. Detalhes pensados.<br>Uma coleção de ideias que ganham forma.",
      "hero.explore": "Ver trabalhos selecionados", "hero.count": "20 projetos",
      "hero.sign": "Portfólio de Nayara J. N. · Brasil",
      "hero.b1": "Trabalhos selecionados / 2026", "hero.b2": "Mundos de marca, objetos & experiências",
      "work.kicker": "A coleção", "work.title": "Trabalhos <em>selecionados</em><sup>20</sup>",
      "work.lede": "Vinte estudos de conceito.<br>Sessenta perspectivas.",
      "work.note": "Todos os projetos aqui são estudos de conceito independentes. As marcas são fictícias.",
      "disc.kicker": "Uma coleção. Muitas expressões.", "disc.title": "Entre<br><em>disciplinas.</em>",
      "disc.text": "Da identidade no papel a um mundo na tela, cada estudo explora uma forma diferente de fazer uma ideia ser sentida.",
      "car.kicker": "A história até aqui", "car.title": "Uma carreira <em>encadernada</em><br>num pequeno livro.",
      "car.text": "Experiência, avaliações de clientes e os trabalhos por trás delas, reunidos num livro. Abra e vire as páginas.",
      "car.s1": "Nota no Workana", "car.s2": "Estudos de conceito", "car.s3": "Anos de Photoshop", "car.s4": "Disciplinas",
      "car.hint": "Clique no livro para abrir",
      "foot.kicker": "Contato", "foot.title": "Boas ideias merecem<br><em>ser vistas.</em>",
      "foot.text": "Envie seu briefing pelo Workana. Respondo em português e inglês, e também recebo briefings em espanhol.",
      "foot.cta": "Contratar no Workana", "foot.note": "Portfólio de conceitos · As marcas são fictícias", "foot.top": "Voltar ao topo",
    },
    es: {
      "skip": "Saltar a los trabajos", "a.langs": "Idioma", "a.filters": "Filtrar proyectos", "a.nav": "Secciones",
      "nav.work": "Trabajos", "nav.disc": "Disciplinas", "nav.career": "Trayectoria", "nav.contact": "Contacto",
      "btn.career": "Mi Carrera", "btn.careerSub": "Abrir el libro",
      "hero.eyebrow": "Dirección de arte · Diseño · Narrativa visual",
      "hero.title": "<span class=\"ln\"><span>Un punto</span></span> <span class=\"ln\"><span>de <em class=\"foil\">vista.</em></span></span>",
      "hero.intro": "Identidades únicas. Detalles cuidados.<br>Una colección de ideas hechas visibles.",
      "hero.explore": "Ver trabajos seleccionados", "hero.count": "20 proyectos",
      "hero.sign": "Portafolio de Nayara J. N. · Brasil",
      "hero.b1": "Trabajos seleccionados / 2026", "hero.b2": "Mundos de marca, objetos y experiencias",
      "work.kicker": "La colección", "work.title": "Trabajos <em>seleccionados</em><sup>20</sup>",
      "work.lede": "Veinte estudios de concepto.<br>Sesenta perspectivas.",
      "work.note": "Todos los proyectos son estudios de concepto independientes. Las marcas son ficticias.",
      "disc.kicker": "Una colección. Muchas expresiones.", "disc.title": "Entre<br><em>disciplinas.</em>",
      "disc.text": "De una identidad en papel a un mundo en pantalla, cada estudio explora una forma distinta de hacer sentir una idea.",
      "car.kicker": "La historia hasta ahora", "car.title": "Una carrera <em>encuadernada</em><br>en un pequeño libro.",
      "car.text": "Experiencia, reseñas de clientes y el trabajo detrás de ellas, reunidos en un libro. Ábrelo y pasa las páginas.",
      "car.s1": "Calificación en Workana", "car.s2": "Estudios de concepto", "car.s3": "Años en Photoshop", "car.s4": "Disciplinas",
      "car.hint": "Haz clic en el libro para abrirlo",
      "foot.kicker": "Contacto", "foot.title": "Las buenas ideas merecen<br><em>ser vistas.</em>",
      "foot.text": "Envíame tu brief por Workana. Respondo en portugués e inglés, y también recibo briefs en español.",
      "foot.cta": "Contrátame en Workana", "foot.note": "Portafolio de conceptos · Las marcas son ficticias", "foot.top": "Volver arriba",
    },
  },
};
