"""Write lqip.js: a tiny blurred preview of every project image.

The page paints these instantly behind each image, so a card never shows up
empty while its real image is still loading.

Run from the project folder after build_images.py:  python tools/build_lqip.py
(build_images.py also runs it at the end.)

img/<slug>-<n>-sm.webp  ->  lqip.js  { "<slug>-<n>": "data:image/svg+xml,..." }
"""
import base64
import io
import json
from pathlib import Path
from urllib.parse import quote

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
IMG = ROOT / "img"
W = 24  # preview width in pixels; the SVG blur hides the blockiness at any size


def preview(path):
    im = Image.open(path).convert("RGB")
    h = max(1, round(im.height * W / im.width))
    buf = io.BytesIO()
    im.resize((W, h), Image.LANCZOS).save(buf, "WEBP", quality=60)
    b64 = base64.b64encode(buf.getvalue()).decode()
    # Blur inside an SVG (as Next.js does) so the preview scales up smoothly; the
    # discrete alpha table keeps the blurred edges fully opaque.
    svg = (
        f"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 {W} {h}' preserveAspectRatio='none'>"
        "<filter id='b' color-interpolation-filters='sRGB'><feGaussianBlur stdDeviation='1.1'/>"
        "<feComponentTransfer><feFuncA type='discrete' tableValues='1 1'/></feComponentTransfer></filter>"
        f"<image width='100%' height='100%' preserveAspectRatio='none' filter='url(#b)' href='data:image/webp;base64,{b64}'/></svg>"
    )
    # Percent-encode everything that could break url(...) in CSS or a style attribute.
    return "data:image/svg+xml," + quote(svg, safe="/:=+;,.-_~")


def build():
    out = {p.name[: -len("-sm.webp")]: preview(p) for p in sorted(IMG.glob("*-sm.webp"))}
    js = (
        "/* Generated by tools/build_lqip.py: blurred previews shown while images load. Do not edit by hand. */\n"
        "window.LQIP = " + json.dumps(out, separators=(",", ":")).replace('","', '",\n"') + ";\n"
    )
    (ROOT / "lqip.js").write_text(js, encoding="utf-8", newline="\n")
    print(f"lqip.js: {len(out)} previews, {len(js) // 1024} KB")


if __name__ == "__main__":
    build()
